name: Build Demo Release APK
on:
  pull_request:
    types: [ 'opened', 'synchronize', 'reopened', 'edited' ]
    branches: [ 'main', 'develop', 'rc/**' ]
jobs:
  Build-Demo-Release:
    runs-on: [ self-hosted, main ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11.0.13
          cache: gradle

      - name: Prepare keystore files
        run: |
          cp $GITHUB_WORKSPACE/../../keystore/keystore_release.properties $GITHUB_WORKSPACE/keystore_release.properties
          cp $GITHUB_WORKSPACE/../../keystore/release.keystore $GITHUB_WORKSPACE/release.keystore

      - name: Run detekt
        run: |
          chmod +x gradlew
          ./gradlew detekt

      - name: Run snapshot tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 24
          force-avd-creation: false
          avd-name: Pixel_4_API_24
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -no-audio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            chmod +x gradlew
            ./gradlew executeScreenshotTests

      - name: Build Demo Release APK
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease
