name: Build Demo Release APK
on:
  pull_request:
    types: ['opened', 'synchronize', 'reopened', 'edited']
    branches: ['main', 'develop', 'rc/**']
jobs:
  Build-Demo-Release:
    runs-on: [self-hosted]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11.0.13
      - name: Prepare keystore files
        run: |
          cp $GITHUB_WORKSPACE/../../keystore/keystore_release.properties $GITHUB_WORKSPACE/keystore_release.properties
          cp $GITHUB_WORKSPACE/../../keystore/release.keystore $GITHUB_WORKSPACE/release.keystore
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Demo Release APK
        run: ./gradlew assembleRelease
